include ~/.config/sway/vars.conf
include ~/.config/theme/sway.conf

# ===== Looks =====
default_border pixel $c_border_width
default_floating_border pixel $c_border_width
gaps inner $c_gaps_inner
gaps outer $c_gaps_outer

# ===== Colors =====
client.focused #ffffff #ffffff #ffffff $c_border_focused $c_border_focused
client.unfocused #ffffff #ffffff #ffffff $c_border_unfocused $c_border_unfocused
