output "*" res 1920x1080 pos 0 0 bg ~/.config/theme/wallpaper fill scale 1

# All workspaces will be on the laptop screen (if the name ePD-1 is correct)
set $laptop "eDP-1" # I don't know if there is a clean way to autodetect this
workspace 1  output $laptop
workspace 2  output $laptop
workspace 3  output $laptop
workspace 4  output $laptop
workspace 5  output $laptop
workspace 6  output $laptop
workspace 7  output $laptop
workspace 8  output $laptop
workspace 9  output $laptop
workspace 10 output $laptop
