#!/usr/bin/env bash
VARPATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/vars"
ENVPATH="$HOME/.local/environment"
GLOBALSPATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/globals"

[ -f "$VARPATH" ] && . "$VARPATH"
[ -f "$GLOBALSPATH" ] && . "$GLOBALSPATH"

# Args: var val -- Sets the variable var to value val in the enviroment.
set_env() {
	local var="$1"
	local val="$2"
	if [ -f "$ENVPATH" ] && grep -q "^export $var=" "$ENVPATH"; then
		sed -i "s|^export $var=.*|export $var=$val|" "$ENVPATH"
	else
		echo "export $var=$val" >> "$ENVPATH"
	fi
	export "$var"="$val"
}

# Args: var val -- Sets the variable var to value val, persistant across sesions.
set_var() {
	local var="$1"
	local val="$2"
	if [ -f "$VARPATH" ] && grep -q "^$var=" "$VARPATH"; then
		sed -i "s|^$var=.*|$var=$val|" "$VARPATH"
	else
		echo "$var=$val" >> "$VARPATH"
	fi
	export "$var"="$val"
}

# Args: prompt_text (text:shortkey:isdef ...) -- 
# Displays prompt and returns value selected by the user. Allows the user to input text or the shortkey (case insensitive). Returns text lowecase.
# If nothing is selected, the field with isdef will be returned if there is any. If more then one field has isdef=true this function will break.
prompt() {
	local prompt_text="$1"
	local options=("${@:2}")
	local default=""
	declare -A ret_map

	if [[ "$prompt_text" != *" " ]]; then
		prompt_text="$prompt_text "
	fi
	prompt_text="$prompt_text["

	for opt in "${options[@]}"; do
		IFS=":" read -r text shortkey isdef <<< "$opt"
		local textl="${text,,}"
		ret_map["${shortkey,,}"]="$textl"
		ret_map["$textl"]="$textl"
		if [[ "$prompt_text" != *"[" ]]; then
			prompt_text="$prompt_text | "
		fi
		prompt_text="$prompt_text$text"
		if [[ "$isdef" == true ]]; then
			default="$textl"
			prompt_text="$prompt_text (default)"
		fi
	done
	prompt_text="$prompt_text]: "

	while true; do
		local input
		read -r -p "$prompt_text" input
		local inputf="$input"
		inputf="${inputf#"${inputf%%[![:space:]]*}"}"
		inputf="${inputf%"${inputf##*[![:space:]]}"}"
		inputf="${inputf,,}"
		if [[ -z "$inputf" ]] && [[ -n "$default"  ]]; then
			echo "$default"
			return 0
		fi
		if [[ -n "${ret_map[$inputf]+x}" ]]; then
			echo "${ret_map[$inputf]}"
			return 0
		fi
		echo "'$input' is not a valid option"
	done
}

# Args: prompt def -- Prompts the user with avaliable options being yes or no, string def should contain "y"/"n"/"". It will return "yes"/"no".
prompt_yn() {
	local prompt="$1"
	local def="$2"
	local default=""

	if [[ "$prompt" != *" " ]]; then
		prompt="$prompt "
	fi

	if [[ "${def,,}" == "y" ]]; then
		prompt="$prompt[Y/n]: "
		default="yes"
	elif [[ "${def,,}" == "n" ]]; then
		prompt="$prompt[y/N]: "
		default="no"
	else
		prompt="$prompt[y/n]: "
	fi

	while true; do 
		local input
		read -r -p "$prompt" input
		local inputf="$input"
		inputf="${inputf#"${inputf%%[![:space:]]*}"}"
		inputf="${inputf%"${inputf##*[![:space:]]}"}"
		inputf="${inputf,,}"

		if [[ -n "$default" ]] && [[ -z "$inputf" ]]; then
			echo "$default"
			return 0
		elif [[ "$inputf" == "yes" ]] || [[ "$inputf" == "ye" ]] || [[ "$inputf" == "y" ]]; then
			echo "yes"
			return 0
		elif [[ "$inputf" == "no" ]] || [[ "$inputf" == "n" ]]; then
			echo "no"
			return 0
		fi

		echo "'$input' is not a valid option"
	done
}
